version: "3.8"
services:
  nginx-guaradata-dev:
    container_name: nginx-guaradata-dev
    build:
      context: ./nginx/dev
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/config/nginx:/etc/nginx
      - ./nginx/dev/share/index.html:/usr/share/nginx/html/index.html
    restart: on-failure:5
    networks:
      guaradata-network-dev:
        ipv4_address: 172.168.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb-guaradata-dev:
    image: mongo:7.0
    container_name: mongodb-guaradata-dev
    restart: always
    volumes:
      - ./nosqldb:/data/db
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}
    ports:
      - 27017:27017
    networks:
      guaradata-network-dev:
        ipv4_address: 172.168.0.3

  postgres-guaradata-dev:
    image: postgres:16.2-alpine
    container_name: postgres-guaradata-dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./sqldb/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      guaradata-network-dev:
        ipv4_address: 172.168.0.4

  mongo-express-dev:
    image: mongo-express
    container_name: mongo-express-dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=${DATABASE_URI}
      - ME_CONFIG_BASICAUTH=${BASICAUTH}
      - ME_CONFIG_BASICAUTH_USERNAME=${BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
    ports:
      - 8081:8081
    depends_on:
      nginx-guaradata-dev:
        condition: service_started
      mongodb-guaradata-dev:
        condition: service_started
      postgres-guaradata-dev:
        condition: service_started
    networks:
      guaradata-network-dev:
        ipv4_address: 172.168.0.6

networks:
  guaradata-network-dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.168.0.0/28
